export const customers = [
  {
    id: 1,
    name: "Tom Cruise",
    phone: "1234567890",
    address: "12, St.John Street,\nChennai - 60001\nTamil Nadu",
  },
  {
    id: 2,
    name: "Virat Kohli",
    phone: "0987654321",
    address: "12, Gandhi Street,\nChennai - 60001\nTamil Nadu",
  },
  {
    id: 3,
    name: "Abdul Kalam",
    phone: "1122334455",
    address: "12, Jawaharlal Nehru Street,\nChennai - 60001\nTamil Nadu",
  },
];

export const indianStates = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry",
];
